package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbhistory<M extends BaseTbhistory<M>> extends Model<M> implements IBean {

	public M setDeviceKey(java.lang.Integer DeviceKey) {
		set("DeviceKey", DeviceKey);
		return (M)this;
	}
	
	public java.lang.Integer getDeviceKey() {
		return getInt("DeviceKey");
	}

	public M setDeviceName(java.lang.String DeviceName) {
		set("DeviceName", DeviceName);
		return (M)this;
	}
	
	public java.lang.String getDeviceName() {
		return getStr("DeviceName");
	}

	public M setTem(java.lang.Double Tem) {
		set("Tem", Tem);
		return (M)this;
	}
	
	public java.lang.Double getTem() {
		return getDouble("Tem");
	}

	public M setHum(java.lang.Double Hum) {
		set("Hum", Hum);
		return (M)this;
	}
	
	public java.lang.Double getHum() {
		return getDouble("Hum");
	}

	public M setRecordTime(java.util.Date RecordTime) {
		set("RecordTime", RecordTime);
		return (M)this;
	}
	
	public java.util.Date getRecordTime() {
		return get("RecordTime");
	}

	public M setIsAlarmData(java.lang.Integer IsAlarmData) {
		set("IsAlarmData", IsAlarmData);
		return (M)this;
	}
	
	public java.lang.Integer getIsAlarmData() {
		return getInt("IsAlarmData");
	}

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

}
