package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTset<M extends BaseTset<M>> extends Model<M> implements IBean {

	public M setDevTempValueMin(java.lang.Double DevTempValueMin) {
		set("DevTempValueMin", DevTempValueMin);
		return (M)this;
	}
	
	public java.lang.Double getDevTempValueMin() {
		return getDouble("DevTempValueMin");
	}

	public M setDevTempValueMax(java.lang.Double DevTempValueMax) {
		set("DevTempValueMax", DevTempValueMax);
		return (M)this;
	}
	
	public java.lang.Double getDevTempValueMax() {
		return getDouble("DevTempValueMax");
	}

	public M setDevHumiValueMax(java.lang.Double DevHumiValueMax) {
		set("DevHumiValueMax", DevHumiValueMax);
		return (M)this;
	}
	
	public java.lang.Double getDevHumiValueMax() {
		return getDouble("DevHumiValueMax");
	}

	public M setDevHumiValueMin(java.lang.Double DevHumiValueMin) {
		set("DevHumiValueMin", DevHumiValueMin);
		return (M)this;
	}
	
	public java.lang.Double getDevHumiValueMin() {
		return getDouble("DevHumiValueMin");
	}

	public M setRecordTime(java.util.Date RecordTime) {
		set("RecordTime", RecordTime);
		return (M)this;
	}
	
	public java.util.Date getRecordTime() {
		return get("RecordTime");
	}

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPhone1(java.lang.String phone1) {
		set("phone1", phone1);
		return (M)this;
	}
	
	public java.lang.String getPhone1() {
		return getStr("phone1");
	}

	public M setPhone2(java.lang.String phone2) {
		set("phone2", phone2);
		return (M)this;
	}
	
	public java.lang.String getPhone2() {
		return getStr("phone2");
	}

	public M setPhone3(java.lang.String phone3) {
		set("phone3", phone3);
		return (M)this;
	}
	
	public java.lang.String getPhone3() {
		return getStr("phone3");
	}

	public M setAlarmTemMax(java.lang.Double AlarmTemMax) {
		set("AlarmTemMax", AlarmTemMax);
		return (M)this;
	}
	
	public java.lang.Double getAlarmTemMax() {
		return getDouble("AlarmTemMax");
	}

	public M setAlarmTemMin(java.lang.Double AlarmTemMin) {
		set("AlarmTemMin", AlarmTemMin);
		return (M)this;
	}
	
	public java.lang.Double getAlarmTemMin() {
		return getDouble("AlarmTemMin");
	}

	public M setAlarmHumMax(java.lang.Double AlarmHumMax) {
		set("AlarmHumMax", AlarmHumMax);
		return (M)this;
	}
	
	public java.lang.Double getAlarmHumMax() {
		return getDouble("AlarmHumMax");
	}

	public M setAlarmHumMin(java.lang.Double AlarmHumMin) {
		set("AlarmHumMin", AlarmHumMin);
		return (M)this;
	}
	
	public java.lang.Double getAlarmHumMin() {
		return getDouble("AlarmHumMin");
	}

}
