package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTconditioner<M extends BaseTconditioner<M>> extends Model<M> implements IBean {

	public M setDeviceKey(java.lang.Integer DeviceKey) {
		set("DeviceKey", DeviceKey);
		return (M)this;
	}
	
	public java.lang.Integer getDeviceKey() {
		return getInt("DeviceKey");
	}

	public M setConditionerName(java.lang.String ConditionerName) {
		set("ConditionerName", ConditionerName);
		return (M)this;
	}
	
	public java.lang.String getConditionerName() {
		return getStr("ConditionerName");
	}

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCOM(java.lang.String COM) {
		set("COM", COM);
		return (M)this;
	}
	
	public java.lang.String getCOM() {
		return getStr("COM");
	}

	public M setBaud(java.lang.Integer Baud) {
		set("Baud", Baud);
		return (M)this;
	}
	
	public java.lang.Integer getBaud() {
		return getInt("Baud");
	}

	public M setSlaveId(java.lang.Integer SlaveId) {
		set("SlaveId", SlaveId);
		return (M)this;
	}
	
	public java.lang.Integer getSlaveId() {
		return getInt("SlaveId");
	}

}
