package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tbalarm", "ID", Tbalarm.class);
		arp.addMapping("tbhistory", "id", Tbhistory.class);
		arp.addMapping("tbsyslog", "ID", Tbsyslog.class);
		arp.addMapping("tchistory", "id", Tchistory.class);
		arp.addMapping("tconditioner", "id", Tconditioner.class);
		arp.addMapping("tequipment", "DeviceKey", Tequipment.class);
		arp.addMapping("tset", "id", Tset.class);
		arp.addMapping("tuser", "id", Tuser.class);
	}
}

