package com.demo.common.model;

import com.demo.common.model.base.BaseTbhistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tbhistory extends BaseTbhistory<Tbhistory> {
	
}
