package com.demo.common.model;

import com.demo.common.model.base.BaseTbsyslog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tbsyslog extends BaseTbsyslog<Tbsyslog> {
	
}
