package com.demo.common.model;

import com.demo.common.model.base.BaseTchistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tchistory extends BaseTchistory<Tchistory> {
	
}
