package com.demo.common.model;

import com.demo.common.model.base.BaseTconditioner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tconditioner extends BaseTconditioner<Tconditioner> {
	
}
