package com.demo.common.model;

import com.demo.common.model.base.BaseTequipment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tequipment extends BaseTequipment<Tequipment> {
	
}
